---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: governance-policy-template-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      name: governance-policy-template-sync
  template:
    metadata:
      labels:
        name: governance-policy-template-sync
    spec:
      serviceAccountName: governance-policy-template-sync
      containers:
        - name: governance-policy-template-sync
          image: quay.io/open-cluster-management/governance-policy-template-sync:latest
          command:
          - governance-policy-template-sync
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: managed
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "governance-policy-template-sync"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: governance-policy-template-sync
subjects:
- kind: ServiceAccount
  name: governance-policy-template-sync
  namespace: open-cluster-management-agent-addon
roleRef:
  kind: ClusterRole
  name: governance-policy-template-sync
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: governance-policy-template-sync-election-rolebinding
subjects:
- kind: ServiceAccount
  name: governance-policy-template-sync
  namespace: open-cluster-management-agent-addon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: governance-policy-template-sync-election-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: governance-policy-template-sync
