apiVersion: apps/v1
kind: Deployment
metadata:
  name: governance-policy-framework-addon
  labels:
    app: governance-policy-framework-addon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: governance-policy-framework-addon
  template:
    metadata:
      labels:
        app: governance-policy-framework-addon
        name: governance-policy-framework-addon
    spec:
      securityContext:
        runAsNonRoot: true
      serviceAccountName: governance-policy-framework-addon
      containers:
        - name: governance-policy-framework-addon
          image: quay.io/open-cluster-management/governance-policy-framework-addon:latest
          command:
            - governance-policy-framework-addon
          args:
            - "--hub-cluster-configfile=/var/run/klusterlet/kubeconfig"
            - --cluster-namespace=managed
            - "--enable-lease=true"
            - "--log-level=2"
            - "--v=0"
          imagePullPolicy: Always
          volumeMounts:
            - name: klusterlet-config
              mountPath: /var/run/klusterlet
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: governance-policy-framework-addon
            - name: DEPLOYMENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app']
          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: klusterlet-config
          secret:
            secretName: hub-kubeconfig
            defaultMode: 420
